trigger:
  branches:
    include:
      - main
      - releases/*

jobs:
  - job: "Build"
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: src/NBS.Appointments.Service/NBS.Appointments.Service.csproj
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: src/NBS.Appointments.Service/NBS.Appointments.Service.csproj
        arguments: '--output publish_output --configuration Release'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: 'publish_output/'
        includeRootFolder: false    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: appointments-service
        dockerfile: src/Dockerfile
        containerRegistry: NbsRegistryServiceConnection
    - task: PublishBuildArtifacts@1
      displayName: "Publish Terraform"
      inputs:
          PathtoPublish: "terraform"
          ArtifactName: "drop_terraform"
          publishLocation: "Container"