trigger:
  branches:
    include:
      - main
      - releases/*

jobs:
  - job: "Build"
    pool:
      vmImage: "windows-latest"
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: src/NBS.Appointments.Service/NBS.Appointments.Service/NBS.Appointments.Service/NBS.Appointments.Service.csproj
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: src/NBS.Appointments.Service/NBS.Appointments.Service/NBS.Appointments.Service/NBS.Appointments.Service.csproj
        arguments: '--output publish_output --configuration Release'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: 'test'
        projects: src/NBS.Appointments.Service/NBS.Appointments.Service/NBS.Appointments.Service.Unit.Tests/NBS.Appointments.Service.Unit.Tests.csproj
    - task: PublishBuildArtifacts@1
      displayName: "Publish Terraform"
      inputs:
          PathtoPublish: "terraform"
          ArtifactName: "drop_terraform"
          publishLocation: "Container"