version: "3.4"

services:
  nbs-appointments-service:
    image: nbsappointmentsservice:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_CONTENTROOT=/azure-functions-host
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AzureWebJobsScriptRoot=/home/site/wwwroot
      - DOTNET_RUNNING_IN_CONTAINER=true
      - FUNCTIONS_WORKER_RUNTIME=dotnet
      - HOST_VERSION=4.15.1
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
    - C:\Users\StephenBanks\AppData\Local\AzureFunctionsTools\Releases\4.30.0\cli_x64_Linux:/functions_debugging_cli:ro
    ports:
    - "32178:80"