version: "3.4"

services:
  api:
    build: .
    image: appointments-service
    ports:
      - "4000:80"

  mock-api:
    image: xmlsolutions/mock-api:3.0
    environment:
      - DataSource=local:./config
      - RoutesFile=setup.json      
    volumes:
      - "./MockResponses:/app/config"
    ports:
      - "4010:80"
